### PR TITLE
feat: use if defined inputs instead of env in action definition

### LINKED ISSUE #19: GitHub Actions Syntax Highlighting fails
The GitHub Actions VS Code extension introduces syntax highlighting in workflow files.

Since the action uses `env` instead of `with` to define the inputs, the following error is shown in the IDE:
image

It would be nice to make use of the inputs instead.

### PR DESCRIPTION
**Pull request by adriencaccia**
fix #19

### CODE REVIEW

**Comment by rez0n** [comment]
Hi @adriencaccia 
Much thanks for your PR.
I'm sorry for very delayed response.

**Comment by adriencaccia** [comment]
No worries!
Thanks for merging 😃

**Comment by zydou** [comment]
This PR is broken, see logs https://github.com/zydou/GFW/actions/runs/5418772706/jobs/9851201362

**Comment by rez0n** [comment]
Hi @zydou 
Thanks on urging this, fix applied, meanwhile needs more testing is both input types works correctly (`with` and `env`)

**Comment by rez0n** [comment]
Hi @adriencaccia @zydou 
I fixed issue, now it supports both `env` and `with` variables assigning. ([test results](https://github.com/rez0n/actions-github-release-test/actions/runs/5494875157))

**Pull request merged**
